#!/usr/bin/env bash
#Configure Nginx server so that /redirect_me is redirecting to another page.

ADD301_REDIRECT="\\\trewrite ^/redirect_me https://www.mbumwa.com permanent;"

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/index.html

sed -i '/server_name _;/a'"$ADD301_REDIRECT" /etc/nginx/sites-available/default

service nginx stop
service nginx start
