#!/usr/bin/env bash
# Adds a custom Nginx response header.

HEADER="\\\t\tadd_header X-Served-By \"$HOSTNAME\";"
sed -i "/^\tlocation \/ {/a""$HEADER" /etc/nginx/sites-available/default

service nginx restart
service nginx reload
