#!/usr/bin/env bash
#Installs and configures HAproxy on a Nginx server.

#install HAProxy
sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy=2.0.\*

[ -f /etc/default/haproxy ] || touch /etc/default/haproxy
[ -f /etc/haproxy/haproxy.cfg ] || touch /etc/haproxy/haproxy.cfg

#enable the HAProxy init script
echo "ENABLED=1" >> /etc/default/haproxy

#HAProxy Configuration: Proxies
#backend
{
	echo ""
	echo -e "backend web-backend"
	echo -e "\tbalance roundrobin"
	echo -e "\tserver web-01 34.229.161.179:80 check"
	echo -e "\tserver web-02 52.201.180.153:80 check"
} >> /etc/haproxy/haproxy.cfg

#frontend
{
	echo ""
	echo "frontend lb-01"
	echo -e "\tbind *:80"
	echo -e "\tmode http"
	echo -e "\tdefault_backend web-backend"
} >> /etc/haproxy/haproxy.cfg

#start HAProxy
if [ "$(pgrep -c haproxy)" -le 0 ]; then
	service haproxy start
else
	service haproxy restart
fi
