#!/usr/bin/env bash
#Installs and configures HAproxy on a Nginx server.

#install HAProxy
apt-get -y update
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get install -y haproxy=2.0.\*

#enable the HAProxy init script
echo "ENABLED=1" >> /etc/default/haproxy

#HAProxy Configuration: Proxies
#frontend and backend
echo '
frontend lb-01-frontend
	bind *:80
	default_backend web-backend

backend web-backend
	balance roundrobin
	server 120363-web-01 34.229.161.179:80
	server 120363-web-02 52.201.180.153:80
' >> /etc/haproxy/haproxy.cfg

#start HAProxy
service haproxy restart
