#!/usr/bin/env bash
#pings an IP address passed as an argument
#Accepts a string as an argument
#Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#Ping the IP 5 times
i=0

if [ $# -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	while [ $i -le 4 ]; do
		ping "$1"
		i=$((i+1))
	done
fi
