#!/usr/bin/env bash
#configures a server to listen on port 80 of all the server’s active IPv4 IPs
sed -i 's/listen 8080 default_server;/listen 80 default_server;/'\
	/etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/'\
	/etc/nginx/sites-enabled/default
sudo service nginx restart
