#!/usr/bin/env bash
#configures a server to listen on port 80 of all the server’s active IPv4 IPs
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
