#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes
#display hours from 0 to 12
hour=0
minute=1
while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	while [ $minute -le 59 ]; do
		echo "$minute"
		minute=$(( minute+1 ))
	done
	minute=1
	hour=$(( hour+1 ))
done
