#!/usr/bin/env bash
#displays numbers from 1 to 100
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
#In a list format
i=1
while [ $i -le 100 ]; do
	echo "$i"
	i=$(( i+1 ))
done

