#!/usr/bin/env bash
#Gets Apache to run on the container and to return a page
#containing Hello Holberton when querying the root of it.
#apt-get update
#apt-get install -y apache2
service apache2 restart
