#!/usr/bin/env bash
#The script should run the whoami command under the user passed as an argument
if [ $# == 0 ]; then
	echo "Usage: ./0-iamsomeoneelse <user>"
else
	USER=$1
	sudo -u "$USER" whoami
fi
